### ISSUE TITLE
Works with linux, no mention in README

### ISSUE THREAD

**Issue by mattrixman** [arvindsv/faketime#5]
I found that doing things "the hard way" allowed me to make this work on linux.  The only difference is that I had to specify the include directories differently and force position independence.  The compile command was:

    gcc -shared -I $JAVA_HOME/include/linux -I $JAVA_HOME/include -fPIC -Wall src/FakeTimeAgent.c -o libfaketime.jnilib

Thought you might like to mention it in the README.

**Comment by arvindsv** [comment]
@mattrixman You're right. I'll add it. It was mentioned in [test_linux_64.sh](https://github.com/arvindsv/faketime/blob/66d6927017afa3e3ed3c0c695da67e2733c709b6/test_linux_64.sh) and [test_linux.sh](https://github.com/arvindsv/faketime/blob/66d6927017afa3e3ed3c0c695da67e2733c709b6/test_linux.sh) scripts, but not in the README.

**Comment by arvindsv** [comment]
Thanks for bringing this up, @mattrixman. I've updated the README. Closing this issue.
