### ISSUE TITLE
jvmti.h not found

### ISSUE THREAD

**Issue by arnzel** [arvindsv/faketime#6]
When run "sh test_linux_64.sh "

i get 

src/FakeTimeAgent.c:5:19: fatal error: jvmti.h: Datei oder Verzeichnis nicht gefunden(File or directory not found)
 #include "jvmti.h"
                   ^
compilation terminated.

**Comment by arnzel** [comment]
Ah its because i di not set Java Home environment variable

**Comment by arvindsv** [comment]
Ah. Cool. I've made a small change to the script to make it show an error if variables are unbound:

```bash
$ ./test_linux_64.sh
./test_linux_64.sh: line 4: JAVA_HOME: unbound variable
```
